version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
