name: Deploy a Vercel + Tests + Discord

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm ci

      - name: Correr tests
        run: npm test

      - name: Build del proyecto
        run: npm run build

      - name: Deploy a Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel pull --yes --environment=production --token "$VERCEL_TOKEN"
          vercel deploy --prod --yes --token "$VERCEL_TOKEN"

      - name: Notificar éxito a Discord
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "username": "GitHub Bot 🤖",
              "embeds": [
                {
                  "title": "🚀 Deploy exitoso en Vercel",
                  "description": "**Proyecto:** coffeweb\n**Branch:** `${{ github.ref_name }}`\n**Autor:** ${{ github.event.head_commit.author.name }}",
                  "color": 65280,
                  "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'",
                  "url": "https://coffeweb-eight.vercel.app",
                  "footer": {
                    "text": "GitHub Actions + Vercel 🌐"
                  }
                }
              ]
            }'

      - name: Notificar error a Discord
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "username": "GitHub Bot 😵",
              "embeds": [
                {
                  "title": "❌ Falló el deploy o los tests",
                  "description": "**Branch:** `${{ github.ref_name }}`\n**Autor:** ${{ github.event.head_commit.author.name }}",
                  "color": 16711680,
                  "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'"
                }
              ]
            }'